SELECT
    MONTH(START_DATE) AS MONTH,
    CAR_ID,
    COUNT(*) AS RECORD
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE CAR_ID IN (
    SELECT
    CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE DATE(START_DATE) BETWEEN DATE('2022-08-01') AND DATE('2022-10-31')
    GROUP BY CAR_ID
    HAVING COUNT(CAR_ID) >= 5
    )
  AND DATE(START_DATE) BETWEEN DATE('2022-08-01') AND DATE('2022-10-31')
GROUP BY YEAR(START_DATE), MONTH(START_DATE), CAR_ID
HAVING COUNT(*) > 0
ORDER BY MONTH ASC, CAR_ID DESC
