WITH A_DEV AS (
    SELECT D.ID, D.EMAIL FROM DEVELOPERS D
    WHERE EXISTS (SELECT 1 FROM SKILLCODES S WHERE S.NAME = 'Python' AND (D.SKILL_CODE & S.CODE) > 0)
      AND EXISTS (SELECT 1 FROM SKILLCODES S WHERE S.CATEGORY = 'Front End' AND (D.SKILL_CODE & S.CODE) > 0)
),
B_DEV AS (
 SELECT D.ID, D.EMAIL FROM DEVELOPERS D
 WHERE EXISTS (SELECT 1 FROM SKILLCODES S WHERE S.NAME = 'C#' AND (D.SKILL_CODE & S.CODE) > 0)
),
C_DEV AS (
 SELECT D.ID, D.EMAIL FROM DEVELOPERS D
 WHERE EXISTS (SELECT 1 FROM SKILLCODES S WHERE S.CATEGORY = 'Front End' AND (D.SKILL_CODE & S.CODE) > 0)
)


SELECT 'A' AS GRADE, ID, EMAIL FROM A_DEV

UNION

SELECT 'B' AS GRADE, ID, EMAIL FROM B_DEV
WHERE ID NOT IN (SELECT ID FROM A_DEV)

UNION

SELECT 'C' AS GRADE, ID, EMAIL FROM C_DEV
WHERE ID NOT IN (SELECT ID FROM A_DEV)
  AND ID NOT IN (SELECT ID FROM B_DEV)

ORDER BY GRADE, ID;

-- 풀이 시간: 26분 , AI 사용: O
-- 아래처럼 풀었다가 틀려서 AI 사용. B에는 A등급의 사람이 들어가면 안 되고, C에는 A와 B 등급의 사람이 들어가면 안되는 것을 생각 못함.

/*
SELECT
    'A' AS GRADE,
    ID,
    EMAIL
FROM DEVELOPERS D
WHERE
    EXISTS (
        SELECT 1
        FROM SKILLCODES S
        WHERE S.NAME = 'Python'
          AND (D.SKILL_CODE & S.CODE) > 0
    )
  AND EXISTS (
    SELECT 1
    FROM SKILLCODES S
    WHERE S.CATEGORY = 'Front End' AND (D.SKILL_CODE & S.CODE) > 0
)

UNION

SELECT
    'B' AS GRADE,
    ID,
    EMAIL
FROM DEVELOPERS D
WHERE
    EXISTS (
        SELECT 1
        FROM SKILLCODES S
        WHERE S.NAME = 'C#' AND (D.SKILL_CODE & S.CODE) > 0
    )

UNION

SELECT
    'C' AS GRADE,
    ID,
    EMAIL
FROM DEVELOPERS D
WHERE
    EXISTS (
        SELECT 1
        FROM SKILLCODES S
        WHERE S.NAME = 'Python' AND (D.SKILL_CODE & S.CODE) = 0
    )
  AND EXISTS (
    SELECT 1
    FROM SKILLCODES S
    WHERE S.CATEGORY = 'Front End' AND (D.SKILL_CODE & S.CODE) > 0
)

ORDER BY GRADE, ID;
 */
