SELECT
    OUTS.ANIMAL_ID,
    OUTS.NAME
FROM ANIMAL_OUTS OUTS
WHERE NOT EXISTS (
    SELECT
        1
    FROM ANIMAL_INS INS
    WHERE INS.ANIMAL_ID = OUTS.ANIMAL_ID
)
ORDER BY OUTS.ANIMAL_ID, OUTS.NAME