SELECT
    O.ANIMAL_ID,
    O.NAME
FROM ANIMAL_OUTS AS O
LEFT JOIN ANIMAL_INS AS I
    ON I.ANIMAL_ID = O.ANIMAL_ID
ORDER BY TIMESTAMPDIFF(MINUTE, I.DATETIME, O.DATETIME) DESC
LIMIT 2;

-- 풀이 시간: 5분, AI 사용: X
