WITH IN_OUT AS (
    SELECT
        INS.ANIMAL_ID,
        INS.NAME,
        INS.DATETIME AS IN_TIME,
        OUTS.DATETIME AS OUT_TIME
    FROM ANIMAL_INS INS
    LEFT JOIN ANIMAL_OUTS OUTS ON INS.ANIMAL_ID = OUTS.ANIMAL_ID
),
NOT_ADAPT AS (
    SELECT * FROM IN_OUT
    WHERE OUT_TIME IS NOT NULL
)

SELECT ANIMAL_ID, NAME FROM NOT_ADAPT
ORDER BY TIMESTAMPDIFF(SECOND, IN_TIME, OUT_TIME) DESC
LIMIT 2;