SELECT
    APNT.APNT_NO,
    PT.PT_NAME,
    PT.PT_NO,
    DR.MCDP_CD,
    DR.DR_NAME,
    APNT.APNT_YMD
FROM APPOINTMENT AS APNT
INNER JOIN PATIENT AS PT
ON APNT.PT_NO = PT.PT_NO
INNER JOIN DOCTOR AS DR
ON APNT.MDDR_ID = DR.DR_ID
WHERE DATE(APNT.APNT_YMD) = '2022-04-13' AND APNT_CNCL_YN = 'N'
ORDER BY APNT_YMD;

-- 풀이 시간: 14분, AI 사용: X
