WITH TEMP AS (
    SELECT DEPT_ID,
           ROUND(AVG(SAL), 0) AS AVG_SAL
    FROM HR_EMPLOYEES
    GROUP BY DEPT_ID
)

SELECT
    T.DEPT_ID,
    HD.DEPT_NAME_EN,
    T.AVG_SAL
FROM HR_DEPARTMENT HD
JOIN TEMP T ON HD.DEPT_ID = T.DEPT_ID
ORDER BY T.AVG_SAL DESC