WITH CHILD_TO_PARENT AS (
    SELECT
        ID,
        PARENT_ID AS PID
    FROM ECOLI_DATA
)

SELECT
    ED.ID,
    COUNT(CTP.PID) AS CHILD_COUNT
FROM ECOLI_DATA ED
         LEFT JOIN CHILD_TO_PARENT CTP ON ED.ID = CTP.PID
GROUP BY ED.ID
ORDER BY ED.ID