-- 정답

SELECT MEMBER_NAME
     , REVIEW_TEXT
     , DATE_FORMAT(REVIEW_DATE, '%Y-%m-%d') AS "REVIEW_DATE"
FROM REST_REVIEW r
         INNER JOIN MEMBER_PROFILE m
                    ON r.MEMBER_ID = m.MEMBER_ID
WHERE r.MEMBER_ID = (SELECT MEMBER_ID
                     FROM REST_REVIEW
                     GROUP BY MEMBER_ID
                     ORDER BY COUNT(REVIEW_SCORE) DESC
    LIMIT 1)
ORDER BY REVIEW_DATE, REVIEW_TEXT

-- 오답

WITH USER_REVIEW AS (
    SELECT
    ROW_NUMBER() OVER (ORDER BY COUNT(REVIEW_SCORE) DESC) AS RNK,
    MEMBER_ID
    FROM REST_REVIEW
    GROUP BY MEMBER_ID
    )

SELECT
    MR.MEMBER_NAME,
    RR.REVIEW_TEXT,
    DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') AS REVIEW_DATE
FROM MEMBER_PROFILE MR
         JOIN REST_REVIEW RR ON MR.MEMBER_ID = RR.MEMBER_ID
         JOIN USER_REVIEW UR ON UR.MEMBER_ID = MR.MEMBER_ID

WHERE UR.RNK = 1

ORDER BY DATE_FORMAT(RR.REVIEW_DATE, '%Y-%m-%d') ASC, RR.REVIEW_TEXT ASC