WITH JOINED_2021 AS (
    SELECT
        USER_ID
    FROM USER_INFO
    WHERE YEAR(JOINED) = '2021'
)

SELECT
    YEAR(SALES_DATE) AS YEAR,
    MONTH(SALES_DATE) AS MONTH,
    COUNT(DISTINCT USER_ID) AS PURCHASED_USERS,
    ROUND(COUNT(DISTINCT USER_ID)/(SELECT COUNT(*) FROM JOINED_2021),1) AS PUCHASED_RATIO
FROM ONLINE_SALE
WHERE USER_ID IN (SELECT USER_ID FROM JOINED_2021)
GROUP BY YEAR, MONTH
ORDER BY YEAR, MONTH;

-- 풀이 시간: 18분 , AI 사용: O COUNT(DISTINCT USER_ID) 대신 COUNT(*)을 해서 틀렸었음.
