WITH USER_2021 AS (
    SELECT
        COUNT(DISTINCT ui.USER_ID) AS USER_COUNT
    FROM USER_INFO ui
    WHERE YEAR(ui.JOINED) = 2021
    ),
    USER_2021_BUY AS (
SELECT
    YEAR(os.SALES_DATE) AS SALES_YEAR,
    MONTH(os.SALES_DATE) AS SALES_MONTH,
    COUNT(DISTINCT ui.USER_ID) AS USER_COUNT
FROM USER_INFO ui
    JOIN ONLINE_SALE os ON ui.USER_ID = os.USER_ID
WHERE YEAR(ui.JOINED) = 2021
GROUP BY YEAR(os.SALES_DATE), MONTH(os.SALES_DATE)
    )

SELECT
    b.SALES_YEAR AS YEAR,
    b.SALES_MONTH AS MONTH,
    b.USER_COUNT AS PURCHASED_USERS,
    ROUND(b.USER_COUNT / t.USER_COUNT, 1) AS PUCHASED_RATIO
FROM USER_2021_BUY b
    CROSS JOIN USER_2021 tz