SELECT
    CONCAT(
            '/home/grep/src/', F.BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT
    ) AS FILE_PATH
FROM USED_GOODS_FILE AS F
JOIN (
    SELECT BOARD_ID FROM USED_GOODS_BOARD ORDER BY VIEWS DESC LIMIT 1
) AS B
ON F.BOARD_ID = B.BOARD_ID
ORDER BY FILE_ID DESC;

-- 풀이 시간: 15분, AI 사용: O CONCAT() 문법에 대해서 찾아봄.
