WITH RARE_PARENT AS (
    SELECT ITEM_ID
    FROM ITEM_INFO
    WHERE RARITY = 'RARE'
)

SELECT
    INFO.ITEM_ID,
    INFO.ITEM_NAME,
    INFO.RARITY
FROM ITEM_TREE TREE
         JOIN RARE_PARENT PARENT ON TREE.PARENT_ITEM_ID = PARENT.ITEM_ID
         JOIN ITEM_INFO INFO ON TREE.ITEM_ID = INFO.ITEM_ID
ORDER BY INFO.ITEM_ID DESC;