WITH FULLTABLE AS (SELECT INS.ANIMAL_ID,
                          INS.NAME,
                          INS.DATETIME  AS IN_TIME,
                          OUTS.DATETIME AS OUT_TIME
                   FROM ANIMAL_INS INS
                            LEFT JOIN ANIMAL_OUTS OUTS ON INS.ANIMAL_ID = OUTS.ANIMAL_ID)

SELECT NAME, IN_TIME AS DATETIME
FROM FULLTABLE
WHERE OUT_TIME IS NULL
ORDER BY IN_TIME ASC LIMIT 3;