WITH RECURSIVE TIME_HOURS AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1 FROM TIME_HOURS WHERE HOUR < 23
)

SELECT
    H.HOUR AS HOUR,
    COUNT(A.ANIMAL_ID) AS COUNT
FROM TIME_HOURS H
LEFT JOIN ANIMAL_OUTS A
    ON H.HOUR = HOUR(A.DATETIME)
GROUP BY H.HOUR
ORDER BY H.HOUR;

-- AI 사용: O Recursive 명령어를 몰랐습니다.
