SELECT
    p.PRODUCT_ID,
    p.PRODUCT_NAME,
    p.PRICE * o.TOTAL_AMOUNT AS TOTAL_SALES
FROM (
     SELECT
         PRODUCT_ID,
         SUM(AMOUNT) AS TOTAL_AMOUNT
     FROM FOOD_ORDER
     WHERE SUBSTRING(PRODUCE_DATE, 1, 7) = '2022-05'
     GROUP BY PRODUCT_ID
) AS o
INNER JOIN FOOD_PRODUCT as p
ON o.PRODUCT_ID = p.PRODUCT_ID
ORDER BY TOTAL_SALES DESC, PRODUCT_ID ASC;
