SELECT 
    FR.PRODUCT_ID,
    FR.PRODUCT_NAME,
    SUM(FR.PRICE * FO.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT FR

JOIN FOOD_ORDER FO ON FO.PRODUCT_ID = FR.PRODUCT_ID

WHERE 
    DATE_FORMAT(FO.PRODUCE_DATE, '%Y-%m') = '2022-05'

GROUP BY FR.PRODUCT_ID

ORDER BY SUM(FR.PRICE * FO.AMOUNT) DESC, FR.PRODUCT_ID ASC
